import * as React from "react"
import { StaticImage } from "gatsby-plugin-image"

const Photogrid = () => {
  return (
    <section className="photogrid-bg">
      <p className="text-center">A small gallery of beautiful flyers from before. The stuff I'm sharing.</p>
      <div className="photogridrow">
        <div className="photogridcol">
          <StaticImage
            className="gridphoto"
            src="../../images/flyer/6.jpeg"
            alt="me"
            placeholder="dominantColor"
          />
          <StaticImage
            className="gridphoto"
            src="../../images/flyer/11.jpeg"
            alt="me"
            placeholder="dominantColor"
          />
          <StaticImage
            className="gridphoto"
            src="../../images/flyer/16.jpeg"
            alt="me"
            placeholder="dominantColor"
          />
          <StaticImage
            className="gridphoto"
            src="../../images/flyer/21.jpeg"
            alt="me"
            placeholder="dominantColor"
          />
          <StaticImage
            className="gridphoto"
            src="../../images/flyer/26.jpeg"
            alt="me"
            placeholder="dominantColor"
          />
          <StaticImage
            className="gridphoto"
            src="../../images/flyer/31.jpeg"
            alt="me"
            placeholder="dominantColor"
          />
          <StaticImage
            className="gridphoto"
            src="../../images/flyer/36.jpeg"
            alt="me"
            placeholder="dominantColor"
          />
        </div>

        <div className="photogridcol">
          <StaticImage
            className="gridphoto"
            src="../../images/flyer/7.jpeg"
            alt="me"
            placeholder="dominantColor"
          />
          <StaticImage
            className="gridphoto"
            src="../../images/flyer/12.jpeg"
            alt="me"
            placeholder="dominantColor"
          />
          <StaticImage
            className="gridphoto"
            src="../../images/flyer/17.jpeg"
            alt="me"
            placeholder="dominantColor"
          />
          <StaticImage
            className="gridphoto"
            src="../../images/flyer/22.jpeg"
            alt="me"
            placeholder="dominantColor"
          />
          <StaticImage
            className="gridphoto"
            src="../../images/flyer/27.jpeg"
            alt="me"
            placeholder="dominantColor"
          />
          <StaticImage
            className="gridphoto"
            src="../../images/flyer/32.jpeg"
            alt="me"
            placeholder="dominantColor"
          />
          <StaticImage
            className="gridphoto"
            src="../../images/flyer/37.jpeg"
            alt="me"
            placeholder="dominantColor"
          />
        </div>

        <div className="photogridcol">
          <StaticImage
            className="gridphoto"
            src="../../images/flyer/3.jpeg"
            alt="me"
            placeholder="dominantColor"
          />
          <StaticImage
            className="gridphoto"
            src="../../images/flyer/13.jpeg"
            alt="me"
            placeholder="dominantColor"
          />
          <StaticImage
            className="gridphoto"
            src="../../images/flyer/18.jpeg"
            alt="me"
            placeholder="dominantColor"
          />
          <StaticImage
            className="gridphoto"
            src="../../images/flyer/23.jpeg"
            alt="me"
            placeholder="dominantColor"
          />
          <StaticImage
            className="gridphoto"
            src="../../images/flyer/28.jpeg"
            alt="me"
            placeholder="dominantColor"
          />
          <StaticImage
            className="gridphoto"
            src="../../images/flyer/33.jpeg"
            alt="me"
            placeholder="dominantColor"
          />
          <StaticImage
            className="gridphoto"
            src="../../images/flyer/38.jpeg"
            alt="me"
            placeholder="dominantColor"
          />
        </div>

        <div className="photogridcol">
          <StaticImage
            className="gridphoto"
            src="../../images/flyer/4.jpeg"
            alt="me"
            placeholder="dominantColor"
          />
          <StaticImage
            className="gridphoto"
            src="../../images/flyer/9.jpeg"
            alt="me"
            placeholder="dominantColor"
          />
          <StaticImage
            className="gridphoto"
            src="../../images/flyer/14.jpeg"
            alt="me"
            placeholder="dominantColor"
          />
          <StaticImage
            className="gridphoto"
            src="../../images/flyer/19.jpeg"
            alt="me"
            placeholder="dominantColor"
          />
          <StaticImage
            className="gridphoto"
            src="../../images/flyer/24.jpeg"
            alt="me"
            placeholder="dominantColor"
          />
          <StaticImage
            className="gridphoto"
            src="../../images/flyer/29.jpeg"
            alt="me"
            placeholder="dominantColor"
          />
          <StaticImage
            className="gridphoto"
            src="../../images/flyer/34.jpeg"
            alt="me"
            placeholder="dominantColor"
          />
        </div>

        <div className="photogridcol">
          <StaticImage
            className="gridphoto"
            src="../../images/flyer/5.jpeg"
            alt="me"
            placeholder="dominantColor"
          />
          <StaticImage
            className="gridphoto"
            src="../../images/flyer/10.jpeg"
            alt="me"
            placeholder="dominantColor"
          />
          <StaticImage
            className="gridphoto"
            src="../../images/flyer/15.jpeg"
            alt="me"
            placeholder="dominantColor"
          />
          <StaticImage
            className="gridphoto"
            src="../../images/flyer/20.jpeg"
            alt="me"
            placeholder="dominantColor"
          />
          <StaticImage
            className="gridphoto"
            src="../../images/flyer/25.jpeg"
            alt="me"
            placeholder="dominantColor"
          />
          <StaticImage
            className="gridphoto"
            src="../../images/flyer/30.jpeg"
            alt="me"
            placeholder="dominantColor"
          />
          <StaticImage
            className="gridphoto"
            src="../../images/flyer/35.jpeg"
            alt="me"
            placeholder="dominantColor"
          />
          <StaticImage
            className="gridphoto"
            src="../../images/flyer/40.jpeg"
            alt="me"
            placeholder="dominantColor"
          />
        </div>
      </div>

    </section>
  )
}
export default Photogrid
