import * as React from "react"
import { StaticImage } from "gatsby-plugin-image"

const Photogrid = () => {
  return (
    <section>
      <div class="photogridrow">
        <div class="photogridcol">
          <StaticImage
            className="gridphoto"
            src="../../images/1.jpeg"
            alt="me"
            placeholder="dominantColor"
          />
          <StaticImage
            className="gridphoto"
            src="../../images/2.jpeg"
            alt="me"
            placeholder="dominantColor"
          />
          <StaticImage
            className="gridphoto"
            src="../../images/3.jpeg"
            alt="me"
            placeholder="dominantColor"
          />
          <StaticImage
            className="gridphoto"
            src="../../images/4.jpeg"
            alt="me"
            placeholder="dominantColor"
          />
          <StaticImage
            className="gridphoto"
            src="../../images/5.jpeg"
            alt="me"
            placeholder="dominantColor"
          />
          <StaticImage
            className="gridphoto"
            src="../../images/6.jpeg"
            alt="me"
            placeholder="dominantColor"
          />
          <StaticImage
            className="gridphoto"
            src="../../images/7.jpeg"
            alt="me"
            placeholder="dominantColor"
          />
          <StaticImage
            className="gridphoto"
            src="../../images/8.jpeg"
            alt="me"
            placeholder="dominantColor"
          />
          <StaticImage
            className="gridphoto"
            src="../../images/9.jpeg"
            alt="me"
            placeholder="dominantColor"
          />
          <StaticImage
            className="gridphoto"
            src="../../images/10.jpeg"
            alt="me"
            placeholder="dominantColor"
          />
        </div>

        <div class="photogridcol">
          <StaticImage
            className="gridphoto"
            src="../../images/11.jpeg"
            alt="me"
            placeholder="dominantColor"
          />
          <StaticImage
            className="gridphoto"
            src="../../images/12.jpeg"
            alt="me"
            placeholder="dominantColor"
          />
          <StaticImage
            className="gridphoto"
            src="../../images/13.jpeg"
            alt="me"
            placeholder="dominantColor"
          />
          <StaticImage
            className="gridphoto"
            src="../../images/14.jpeg"
            alt="me"
            placeholder="dominantColor"
          />
          <StaticImage
            className="gridphoto"
            src="../../images/15.jpeg"
            alt="me"
            placeholder="dominantColor"
          />
          <StaticImage
            className="gridphoto"
            src="../../images/16.jpeg"
            alt="me"
            placeholder="dominantColor"
          />
          <StaticImage
            className="gridphoto"
            src="../../images/17.jpeg"
            alt="me"
            placeholder="dominantColor"
          />
          <StaticImage
            className="gridphoto"
            src="../../images/18.jpeg"
            alt="me"
            placeholder="dominantColor"
          />
          <StaticImage
            className="gridphoto"
            src="../../images/19.jpeg"
            alt="me"
            placeholder="dominantColor"
          />
          <StaticImage
            className="gridphoto"
            src="../../images/20.jpeg"
            alt="me"
            placeholder="dominantColor"
          />
        </div>

        <div class="photogridcol">
          <StaticImage
            className="gridphoto"
            src="../../images/21.jpeg"
            alt="me"
            placeholder="dominantColor"
          />
          <StaticImage
            className="gridphoto"
            src="../../images/22.jpeg"
            alt="me"
            placeholder="dominantColor"
          />
          <StaticImage
            className="gridphoto"
            src="../../images/23.jpeg"
            alt="me"
            placeholder="dominantColor"
          />
          <StaticImage
            className="gridphoto"
            src="../../images/24.jpeg"
            alt="me"
            placeholder="dominantColor"
          />
          <StaticImage
            className="gridphoto"
            src="../../images/25.jpeg"
            alt="me"
            placeholder="dominantColor"
          />
          <StaticImage
            className="gridphoto"
            src="../../images/26.jpeg"
            alt="me"
            placeholder="dominantColor"
          />
          <StaticImage
            className="gridphoto"
            src="../../images/27.jpeg"
            alt="me"
            placeholder="dominantColor"
          />
          <StaticImage
            className="gridphoto"
            src="../../images/28.jpeg"
            alt="me"
            placeholder="dominantColor"
          />
          <StaticImage
            className="gridphoto"
            src="../../images/29.jpeg"
            alt="me"
            placeholder="dominantColor"
          />
          <StaticImage
            className="gridphoto"
            src="../../images/30.jpeg"
            alt="me"
            placeholder="dominantColor"
          />
        </div>

        <div class="photogridcol">
          <StaticImage
            className="gridphoto"
            src="../../images/31.jpeg"
            alt="me"
            placeholder="dominantColor"
          />
          <StaticImage
            className="gridphoto"
            src="../../images/32.jpeg"
            alt="me"
            placeholder="dominantColor"
          />
          <StaticImage
            className="gridphoto"
            src="../../images/33.jpeg"
            alt="me"
            placeholder="dominantColor"
          />
          <StaticImage
            className="gridphoto"
            src="../../images/34.jpeg"
            alt="me"
            placeholder="dominantColor"
          />
          <StaticImage
            className="gridphoto"
            src="../../images/35.jpeg"
            alt="me"
            placeholder="dominantColor"
          />
          <StaticImage
            className="gridphoto"
            src="../../images/36.jpeg"
            alt="me"
            placeholder="dominantColor"
          />
          <StaticImage
            className="gridphoto"
            src="../../images/37.jpeg"
            alt="me"
            placeholder="dominantColor"
          />
          <StaticImage
            className="gridphoto"
            src="../../images/38.jpeg"
            alt="me"
            placeholder="dominantColor"
          />
          <StaticImage
            className="gridphoto"
            src="../../images/39.jpeg"
            alt="me"
            placeholder="dominantColor"
          />
          <StaticImage
            className="gridphoto"
            src="../../images/40.jpeg"
            alt="me"
            placeholder="dominantColor"
          />
        </div>

        <div class="photogridcol">
          <StaticImage
            className="gridphoto"
            src="../../images/41.jpeg"
            alt="me"
            placeholder="dominantColor"
          />
          <StaticImage
            className="gridphoto"
            src="../../images/42.jpeg"
            alt="me"
            placeholder="dominantColor"
          />
          <StaticImage
            className="gridphoto"
            src="../../images/43.jpeg"
            alt="me"
            placeholder="dominantColor"
          />
          <StaticImage
            className="gridphoto"
            src="../../images/44.jpeg"
            alt="me"
            placeholder="dominantColor"
          />
          <StaticImage
            className="gridphoto"
            src="../../images/45.jpeg"
            alt="me"
            placeholder="dominantColor"
          />
          <StaticImage
            className="gridphoto"
            src="../../images/46.jpeg"
            alt="me"
            placeholder="dominantColor"
          />
          <StaticImage
            className="gridphoto"
            src="../../images47.jpeg"
            alt="me"
            placeholder="dominantColor"
          />
          <StaticImage
            className="gridphoto"
            src="../../images/48.jpeg"
            alt="me"
            placeholder="dominantColor"
          />
          <StaticImage
            className="gridphoto"
            src="../../images/49.jpeg"
            alt="me"
            placeholder="dominantColor"
          />
          <StaticImage
            className="gridphoto"
            src="../../images/50.jpeg"
            alt="me"
            placeholder="dominantColor"
          />
        </div>
      </div>
      <p className="text-center pt-7">
        Got some cool pics you'd like to share?
        <br />
        <a href="mailto:partypics@sli.st">partypics@sli.st</a>
      </p>
    </section>
  )
}
export default Photogrid
